### ISSUE TITLE
Task "IsActive" is always null

### ISSUE THREAD

**Issue by vbettoni** [johnbabb/C--Toggl-Api-Client#10]
In object "Task", there is a property to get / set if the task is active or done (nullable boolean value).

Your Task data object has the following property:
[JsonProperty(PropertyName = "is_active")]
public bool? IsActive { get; set; }

while JSON object sent by Toggl is as follow
[{"id":18072471,"name":"1399315 - Release - Bug Fix","wid":1926627,"pid":75477014,"active":true,"at":"2018-01-19T16:15:43+00:00","estimated_seconds":0,"tracked_seconds":19431}]

IsActive in JSON is "active" instead of "is_active". 

You just need to change the Attribute to active instead of is_active and everything should be fine.

Thanks

**Comment by johnbabb** [comment]
resolved [see here](https://github.com/johnbabb/C--Toggl-Api-Client/commit/5e4f034b6de4f39d5d23d46b0b1a28c7a0a821fb)
